### ISSUE TITLE
Relax `base` and `haskeline` upper bounds

### ISSUE THREAD

**Issue by andreasabel** [pylover/hangman-game#1]
Allow to build with newer GHCs. See 
- https://github.com/pylover/hangman-ascii/commit/574d408656a4ad7cb1b71a063609acf99e3153e0#r73083794

**Comment by pylover** [comment]
I'm new to Haskell and thanks a lot for the advice.

**Comment by pylover** [comment]
Done, Sorry for the late.

https://hackage.haskell.org/package/HangmanAscii-0.1.1.1
